### Задание 1  
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [1]:
import numpy as np

In [14]:
array_np = np.arange(9, -1, -1)
array_np

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2  
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [16]:
matrix_np = np.diag(array_np, k=0)
matrix_np

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
sum(np.diagonal(matrix_np))

45

### Задание 3  
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [23]:
a = np.array( 
    [
        [4, 2, 1],
        [1, 3, 0],
        [0, 5, 4]
    ] 
)
b = np.array( 
    [
        [4], [12], [-3]
    ] 
)

In [24]:
from numpy import linalg
linalg.solve(a, b)


array([[ 0.46666667],
       [ 3.84444444],
       [-5.55555556]])

In [25]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
    

In [26]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [42]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [43]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [46]:
max_cos = 0
i = 0
for elem in users_stats:
    if cosine(elem, next_user_stats) >= max_cos:
        max_cos = cosine(elem, next_user_stats)
        max_id = i
    i += 1
print(max_cos, max_id)

0.9486832980505138 7
